name: push output

on:
  push:
    paths:
    - 'input/**.docx'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Ant
      run: ant -noinput -buildfile build.xml -lib ./lib
    - name: Commit files
      run: |
        git config --local user.email [mail]
        git config --local user.name [user]
        git add ./output
        git commit -m "Update output"
    - name: Push changes
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@master
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'output'
          destination-github-username: 'gwolbers'
          destination-repository-name: 'test_workflow_dev'
          user-email: 'g.wolbers@geonovum.nl'
          commit-message: See ORIGIN_COMMIT from $GITHUB_REF
          target-branch: 'master'
    - name: Test get variable exported by push-to-another-repository
      run: echo $DESTINATION_CLONED_DIRECTORY
